# -*- coding: utf-8 -*-
"""Gemini_API_Exploration.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iFFaRugufA-j0AaBBl6wVBd11WJQrDNK
"""

pip install -q -U google-generativeai

import google.generativeai as genai
import os

# Set your API key
os.environ["GOOGLE_API_KEY"] = "YOUR API KEY"
genai.configure(api_key=os.environ["GOOGLE_API_KEY"])

# Function to list available models
def list_available_models():
    models = genai.list_models()
    for model in models:
        print("====================================================--------------------------")
        print(f"Model Name: {model.name}, \n Description: {getattr(model, 'description', 'No description available')}")
        print("====================================================--------------------------")

# Call the function to list models
list_available_models()

# Initialize the model
model = genai.GenerativeModel("models/gemini-pro")

prompt = "What is universe"

model.generate_content(prompt).text

"""Structure Code"""

# Function to generate content
def generate_contet(prompt):
    response = model.generate_content(prompt)
    return response.text

#
prompt = input("How may i help Today............")
content = generate_contet(prompt)

print("\n\n==================================\n",content)